# Generated by Django 5.1.2 on 2024-10-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wheat", models.IntegerField(default=0)),
                ("flour", models.IntegerField(default=0)),
                ("water", models.IntegerField(default=0)),
                ("salt", models.IntegerField(default=0)),
                ("dish", models.CharField(max_length=32)),
                ("is_adult", models.BooleanField(default=True)),
            ],
        ),
    ]
